services:
  gitlab:
    image: gitlab/gitlab-ce:18.10.3-ce.0
    container_name: gitlab
    restart: unless-stopped
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.ebbez.dev'
        nginx['listen_port'] = 80
        nginx['listen_https'] = false

        pages_external_url 'https://pages.ebbez.dev'
        pages_nginx['enable'] = true
        pages_nginx['listen_port'] = 80
        pages_nginx['listen_https'] = false
        gitlab_pages['namespace_in_path'] = true
        gitlab_pages['access_control'] = true

        puma['worker_processes'] = 0
        sidekiq['concurrency'] = 5

        gitaly['env'] = {
          'GITALY_COMMAND_SPAWN_MAX_PARALLEL' => '2',
          'MALLOC_CONF' => 'dirty_decay_ms:1000,muzzy_decay_ms:1000'
        }

        prometheus_monitoring['enable'] = false

        gitlab_rails['env'] = {
          'MALLOC_CONF' => 'dirty_decay_ms:1000,muzzy_decay_ms:1000'
        }
    networks:
      - default
      - reverse_proxy
    ports:
      - '222:22'
    volumes:
      - './config:/etc/gitlab'
      - './logs:/var/log/gitlab'
      - './data:/var/opt/gitlab'

  runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    restart: unless-stopped
    depends_on:
      - gitlab
    volumes:
      - 'runner:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock'

volumes:
  runner:

networks:
  reverse_proxy:
    external: true
